version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0-buster
    steps:
      - checkout # check out the code in the project directory
      - run: curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt-get update
      - run: sudo apt install google-chrome-stable
      - run: sudo apt-get install libgconf-2-4
      - run: npm i
      - run: CI=true npm run test
      - run: sudo npm i forever -g
      - run: forever start -c "npm start" ./
      - run: npx cypress run --spec "cypress/integration/app_light.spec.ts"
      - run: npx testcafe chrome:headless testcafe/test1_light.ts
