// Album List Api Action Type
export const LIST_ALBUMS_START = 'LIST_ALBUMS_START';
export const LIST_ALBUMS_SUCCEED = 'LIST_ALBUMS_SUCCEED';
export const LIST_ALBUMS_FAIL = 'LIST_ALBUMS_FAIL';

// Album Create Api Action Type
export const CREATE_ALBUM_START = 'CREATE_ALBUM_START';
export const CREATE_ALBUM_SUCCEED = 'CREATE_ALBUM_SUCCEED';
export const CREATE_ALBUM_FAIL = 'CREATE_ALBUM_FAIL';

// Album Delete Api Action Type
export const DELETE_ALBUM_START = 'DELETE_ALBUM_START';
export const DELETE_ALBUM_SUCCEED = 'DELETE_ALBUM_SUCCEED';
export const DELETE_ALBUM_FAIL = 'DELETE_ALBUM_FAIL';

// Album Api Initialize
export const ALBUMS_API_INITIALIZE = 'ALBUMS_API_INITIALIZE';
